name: CI build

on:
  push:
    branches: [ master ]
  # TODO(aptny): how are secrets handled for forks/pulls?
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]
        include:
          - os: windows-latest
            deploy_tool: windeployqt
            target_name: toucan-ui.exe
    runs-on: ${{ matrix.os }}

    steps:
    - uses: ilammy/msvc-dev-cmd@v1
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v1
      with:
        path: ../Qt
        key: qt-${{ runner.os }}
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        cached: ${{ steps.cache-qt.outputs.cache-hit }}
        version: "5.15.0"
    - id: dw-rev
      shell: bash
      run: |
        mkdir widgets_build
        echo "::set-output name=hash::$(git rev-parse HEAD)"
    - name: Cache DeclarativeWidgets build
      id: cache-dw
      uses: actions/cache@v1
      with:
        path: widgets_build
        key: dw-${{ runner.os }}-${{ steps.dw-rev.outputs.hash }}
    - name: DeclarativeWidgets build
      if: ${{ !steps.cache-dw.outputs.cache-hit }}
      working-directory: widgets_build
      run: |
        qmake ..\3p\DeclarativeWidgets\declarativewidgets.pro
        nmake
    - name: cargo build
      uses: actions-rs/cargo@v1
      with:
        command: build
    - name: QT deploy
      run: >
        ${{ matrix.deploy_tool }} --dir out/
        --qmldir frontend/qml/
        --qmlimport widgets_build/qml/
        target/debug/${{ matrix.target_name }}
    - name: Package release (Windows)
      if: matrix.os == "windows-latest"
      run: Compress-Archive -Path out/ -DestinationPath toucan-ui.zip
    - name: Package release (Unix)
      if: matrix.os != "windows-latest"
      run: zip -r out toucan-ui.zip
    - uses: "marvinpinto/action-automatic-releases@v1.1.0"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        files: toucan-ui.zip
    
